#!/bin/bash
#
# setup-hardware-controls.sh - Set up hardware controls for ASUSTOR Flashstor 6
#
# This script:
# 1. Installs fancontrol configuration for automatic fan curves
# 2. Creates LED trigger service for disk activity indicators
# 3. Ensures asustor-platform-driver modules load at boot
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

# Check root
if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root"
    exit 1
fi

log_info "Setting up ASUSTOR Flashstor 6 hardware controls..."

# 1. Ensure kernel modules load at boot
log_info "Configuring kernel modules..."
cat > /etc/modules-load.d/asustor.conf << 'EOF'
# ASUSTOR platform driver modules
asustor
asustor_it87
EOF

# Load modules now if not already loaded
modprobe asustor 2>/dev/null || true
modprobe asustor_it87 2>/dev/null || true

# 2. Install fancontrol configuration
log_info "Installing fancontrol configuration..."

# Install fancontrol if not present
if ! command -v fancontrol &>/dev/null; then
    apt-get update
    apt-get install -y lm-sensors fancontrol
fi

# Find the correct hwmon numbers (they can change between boots)
IT8625_HWMON=""
CORETEMP_HWMON=""

for hwmon in /sys/class/hwmon/hwmon*; do
    name=$(cat "$hwmon/name" 2>/dev/null || echo "")
    case "$name" in
        it8625) IT8625_HWMON=$(basename "$hwmon") ;;
        coretemp) CORETEMP_HWMON=$(basename "$hwmon") ;;
    esac
done

if [[ -z "$IT8625_HWMON" || -z "$CORETEMP_HWMON" ]]; then
    log_error "Could not find required hwmon devices (it8625=$IT8625_HWMON, coretemp=$CORETEMP_HWMON)"
    exit 1
fi

log_info "Found hwmon devices: IT8625=$IT8625_HWMON, coretemp=$CORETEMP_HWMON"

# Generate fancontrol config with correct hwmon paths
cat > /etc/fancontrol << EOF
# ASUSTOR Flashstor 6 (FS6706T) fancontrol configuration
# Generated by setup-hardware-controls.sh
#
# Fan curve based on CPU temperature:
#   - Below 40°C: ~30% (quiet)
#   - 40-65°C: Linear ramp to 100%
#   - Above 65°C: 100% (full speed)

INTERVAL=5
DEVPATH=$IT8625_HWMON=devices/platform/asustor_it87.2608 $CORETEMP_HWMON=devices/platform/coretemp.0
DEVNAME=$IT8625_HWMON=it8625 $CORETEMP_HWMON=coretemp
FCTEMPS=$IT8625_HWMON/pwm1=$CORETEMP_HWMON/temp1_input
FCFANS=$IT8625_HWMON/pwm1=$IT8625_HWMON/fan1_input
MINTEMP=$IT8625_HWMON/pwm1=40
MAXTEMP=$IT8625_HWMON/pwm1=65
MINSTART=$IT8625_HWMON/pwm1=80
MINSTOP=$IT8625_HWMON/pwm1=80
MINPWM=$IT8625_HWMON/pwm1=80
MAXPWM=$IT8625_HWMON/pwm1=255
EOF

log_info "Fancontrol configuration installed to /etc/fancontrol"

# Enable and start fancontrol
systemctl enable fancontrol
systemctl restart fancontrol || log_warn "fancontrol failed to start (may need reboot)"

# 3. Create LED trigger service
log_info "Creating LED trigger service..."

cat > /etc/systemd/system/asustor-leds.service << 'EOF'
[Unit]
Description=ASUSTOR LED Triggers Configuration
After=multi-user.target
Wants=multi-user.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/local/bin/asustor-led-setup.sh

[Install]
WantedBy=multi-user.target
EOF

# Create LED setup script
cat > /usr/local/bin/asustor-led-setup.sh << 'LEDSCRIPT'
#!/bin/bash
#
# ASUSTOR LED setup script - runs at boot
# Sets LED triggers for disk activity and network status
#

LEDS="/sys/class/leds"

# Helper function
set_led() {
    local led="$1"
    local trigger="$2"
    local brightness="${3:-1}"

    if [[ -d "$LEDS/$led" ]]; then
        echo "$trigger" > "$LEDS/$led/trigger" 2>/dev/null || true
        echo "$brightness" > "$LEDS/$led/brightness" 2>/dev/null || true
    fi
}

# Find IT8625 hwmon for blink control
for hwmon in /sys/class/hwmon/hwmon*; do
    if [[ "$(cat "$hwmon/name" 2>/dev/null)" == "it8625" ]]; then
        IT8625_HWMON="$hwmon"
        break
    fi
done

# Power LED - solid blue when on
set_led "blue:power" "none" 1
set_led "red:power" "none" 0

# Status LED - heartbeat pattern (shows system is alive)
set_led "green:status" "heartbeat" 1
set_led "red:status" "panic" 0

# LAN LED - blink on network activity
set_led "blue:lan" "netdev" 1

# NVMe disk LEDs - blink on disk activity
set_led "nvme1:green:disk" "disk-activity" 1
set_led "nvme1:red:disk" "none" 0

# Side accent LEDs - on by default (can be turned off for stealth)
set_led "red:side_inner" "none" 1
set_led "red:side_mid" "none" 1
set_led "red:side_outer" "none" 1

# Disable annoying IT8625 hardware blink (use software triggers instead)
if [[ -n "$IT8625_HWMON" ]]; then
    echo 0 > "$IT8625_HWMON/gpled1_blink" 2>/dev/null || true
fi

echo "ASUSTOR LED triggers configured"
LEDSCRIPT

chmod +x /usr/local/bin/asustor-led-setup.sh

# Copy to repo config for reference
mkdir -p "$REPO_DIR/config/systemd"
cp /etc/systemd/system/asustor-leds.service "$REPO_DIR/config/systemd/" 2>/dev/null || true

# Enable and run LED service
systemctl daemon-reload
systemctl enable asustor-leds.service
systemctl start asustor-leds.service

log_info "LED trigger service installed and started"

# 4. Summary
echo ""
log_info "Hardware controls setup complete!"
echo ""
echo "Services enabled:"
echo "  - fancontrol: Automatic fan speed based on CPU temp (40-65°C ramp)"
echo "  - asustor-leds: LED triggers (disk activity, heartbeat, network)"
echo ""
echo "Commands:"
echo "  ./scripts/hardware-control.sh status   - Show hardware status"
echo "  ./scripts/hardware-control.sh fan auto - Enable automatic fan"
echo "  ./scripts/hardware-control.sh side off - Turn off side LEDs"
echo ""
echo "Configuration files:"
echo "  /etc/fancontrol                        - Fan curve configuration"
echo "  /usr/local/bin/asustor-led-setup.sh   - LED trigger script"
echo ""
